# SPDX-License-Identifier: Apache-2.0

load("//build:wdb_case.bzl", "wdb_case")

package(default_visibility = ["//visibility:public"])

wdb_case(
    name = "t81_pkt_1con____",
    # Compilation order matters to xvhdl; do not sort.
    # do not sort
    srcs = [
        "pk.pkg.vhdl",
        "tb.ent.vhdl",
    ],
)
