load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "wdb",
    srcs = [
        "diff.go",
        "probe.go",
    ],
    importpath = "git.hdlfactory.com/HDL/wdbcvt/pkg/wdb",
    visibility = ["//visibility:public"],
)

go_test(
    name = "wdb_test",
    srcs = [
        "diff_test.go",
        "probe_test.go",
    ],
    embed = [":wdb"],
)
