load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "wdb",
    srcs = [
        "container.go",
        "debug.go",
        "diff.go",
        "dump.go",
        "file.go",
        "pages.go",
        "probe.go",
        "stream.go",
        "types.go",
        "value.go",
        "verilog.go",
    ],
    importpath = "git.hdlfactory.com/HDL/wdbcvt/pkg/wdb",
    visibility = ["//visibility:public"],
)

go_test(
    name = "wdb_test",
    size = "medium",
    srcs = [
        "corpus_test.go",
        "debug_test.go",
        "diff_test.go",
        "probe_test.go",
        "stream_test.go",
        "vcd_test.go",
    ],
    data = [
        "//hdl/corpus:all_truth",
        "//hdl/corpus:all_wdb",
        "//hdl/counter:sim",
        "//hdl/ibex:sim",
        "//hdl/neorv32:sim",
        "//hdl/picorv32:sim",
        "//hdl/potato:sim",
        "//hdl/serv:sim",
        "//hdl/uart:sim",
    ],
    embed = [":wdb"],
    deps = ["@com_github_filmil_go_vcd_parser//vcd"],
)
