# SPDX-License-Identifier: Apache-2.0

load("//build:wdb_case.bzl", "wdb_case")

package(default_visibility = ["//visibility:public"])

wdb_case(
    name = "t83_rec_nested__",
    srcs = [
        "tb.ent.vhdl",
    ],
    xelab_args = [
        "-debug",
        "typical",
        "-debug",
        "subprogram",
    ],
)
