# SPDX-License-Identifier: Apache-2.0

load("//build:wdb_case.bzl", "wdb_case")

package(default_visibility = ["//visibility:public"])

wdb_case(
    name = "t79_frm_two_64__",
    srcs = [
        "tb.ent.vhdl",
    ],
    xelab_args = [
        "-debug",
        "typical",
        "-debug",
        "subprogram",
    ],
)
