load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "gen_t61_lib",
    srcs = ["main.go"],
    importpath = "git.hdlfactory.com/HDL/wdbcvt/tools/corpus/gen_t61",
    visibility = ["//visibility:private"],
    deps = [
        "//tools/corpus/gencommon",
        "//tools/corpus/gent60",
    ],
)

go_binary(
    name = "gen_t61",
    embed = [":gen_t61_lib"],
    visibility = ["//visibility:public"],
)
