load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "wdbcvt_lib",
    srcs = ["main.go"],
    importpath = "git.hdlfactory.com/HDL/wdbcvt/cmd/wdbcvt",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/fstout",
        "//pkg/wdb",
    ],
)

go_binary(
    name = "wdbcvt",
    embed = [":wdbcvt_lib"],
    visibility = ["//visibility:public"],
)
